### ISSUE TITLE
Why include entire LLVM history?

### ISSUE THREAD

**Issue by refi64** [weliveindetail/llvm-expected#1]
This makes a `git clone` really, really, *REALLY* slow...

**Comment by refi64** [comment]
Ah, I'm assuming [this](https://github.com/weliveindetail/llvm-expected/commit/657d0df0ff24cd581274e87663e243c3f791c7b9) is the answer...

**Comment by weliveindetail** [comment]
That's true, but in a way intended to simplify licensing. I will double-check if cutting the history is fine with the LLVM license and push a shallow clone. For now please consider a shallow copy.

**Comment by weliveindetail** [comment]
Yes I just added the note to the readme. Thanks for pointing this out.
