### ISSUE TITLE
Linking more than one object including llvm-expected.h fails

### ISSUE THREAD

**Issue by Toizi** [weliveindetail/llvm-expected#3]
Executing build.sh from the attached sample leads to a multiple definition error:
```
lib.obj: In function `llvm::llvm_unreachable_internal(char const*, char const*, unsigned int)':
lib.cpp:(.text+0x0): multiple definition of `llvm::llvm_unreachable_internal(char const*, char const*, unsigned int)'
test.obj:test.cpp:(.text+0x0): first defined here
clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
```

Latest clang
```
clang++ --version
clang version 7.0.1 (tags/RELEASE_701/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

Adding `inline` to the definition of `llvm_unreachable_internal` makes the error go away

[llvm-expected-sample.tar.gz](https://github.com/weliveindetail/llvm-expected/files/2872961/llvm-expected-sample.tar.gz)

**Comment by weliveindetail** [comment]
Oh that sounds reasonable. Thanks for catching this one! Can you possibly make a PR for it? Thks
